routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
})->middleware('auth');

Auth::routes();

Route::get('/', 'DashboardController@index');
Route::get('/dashboard', 'DashboardController@index');
// Route::get('/system-management/{option}', 'SystemMgmtController@index');
Route::resource('profile', 'ProfileController'); 
Route::get('/profile', 'ProfileController@index');
Route::post('/profile/update', 'ProfileController@update')->name('profile.update');

Route::post('user-management/search', 'UserManagementController@search')->name('user-management.search');
Route::resource('user-management', 'UserManagementController');

Route::resource('employee-management', 'EmployeeManagementController');
Route::post('employee-management/search', 'EmployeeManagementController@search')->name('employee-management.search');

Route::resource('system-management/department', 'DepartmentController');
Route::post('system-management/department/search', 'DepartmentController@search')->name('department.search');

Route::resource('system-management/division', 'DivisionController');
Route::post('system-management/division/search', 'DivisionController@search')->name('division.search');

Route::resource('system-management/country', 'CountryController');
Route::post('system-management/country/search', 'CountryController@search')->name('country.search');
 
Route::resource('system-management/state', 'StateController');
Route::post('system-management/state/search', 'StateController@search')->name('state.search');

Route::resource('system-management/city', 'CityController');
Route::post('system-management/city/search', 'CityController@search')->name('city.search');

Route::resource('system-management/machine', 'MachineController');
Route::post('system-management/machine/search', 'MachineController@search')->name('machine.search');

Route::resource('system-management/service', 'ServicesController');
Route::post('system-management/service/search', 'ServicesController@search')->name('service.search');

Route::resource('system-management/service-category', 'ServicesCategoryController');
Route::post('system-management/service-category/search', 'ServicesCategoryController@search')->name('service-category.search');

Route::resource('system-management/sla', 'SlaController');
Route::post('system-management/sla/search', 'SlaController@search')->name('sla.search');

Route::resource('partners', 'PartnersController');
Route::post('partners/search', 'PartnersController@search')->name('partners.search');
Route::post('partners/add-coverage/{id}', 'PartnersController@addCoverage')->name('partners.addcoverage');
 
Route::resource('contract', 'ContractsController'); 
Route::get('contract-update', 'ContractsController@updatedata')->name('contract.updatedata');
Route::get('contract/{contract}/delete-machine/{id}', 'ContractsController@destroydetail')->name('contract.deletemachine');
Route::post('contract/update-machine', 'ContractsController@updatemachine')->name('contract.updatemachine');
Route::post('contract/search', 'ContractsController@search')->name('contract.search');

Route::resource('customer', 'CustomerController'); 
Route::post('customer/search', 'CustomerController@search')->name('customer.search');

Route::resource('ticketing', 'TicketingController'); 
Route::post('ticketing/change-technician/{id}', 'TicketingController@updateTechnician')->name('ticketing.update-technician');
Route::get('ticketing-emergency', 'TicketingController@emergency')->name('ticketing.emergencys');
Route::get('ticketing-finish', 'TicketingController@finish')->name('ticketing.finishs');

Route::get('ticketing/approve-request/{id}/{ticket_id}', 'TicketingController@approveRequest')->name('ticketing.approverequest');
Route::get('ticketing/reject-request/{id}/{ticket_id}', 'TicketingController@rejectRequest')->name('ticketing.rejectrequest');
Route::get('ticketing/cancel-request/{id}/{ticket_id}', 'TicketingController@cancelRequest')->name('ticketing.cancelrequest');
Route::post('ticketing/add-request/{id}', 'TicketingController@addRequest')->name('ticketing.addrequest');
Route::post('ticketing/update-request/{id}', 'TicketingController@updateRequest')->name('ticketing.updaterequest');

Route::get('ticketing/closed/{ticket_id}', 'TicketingController@closed')->name('ticketing.closed');
Route::get('ticketing/decline-closed/{ticket_id}', 'TicketingController@declineClosed')->name('ticketing.declineclosed');
Route::get('ticketing/approve-closed/{ticket_id}', 'TicketingController@approveClosed')->name('ticketing.approveclosed');
Route::post('ticketing/search', 'TicketingController@search')->name('ticketing.search');
Route::get('ticketing/add/{id}', 'TicketingController@add')->name('ticketing.add');
Route::post('ticketing/add-action/{id}', 'TicketingController@addAction')->name('ticketing.addaction');


Route::get('system-management/report', 'ReportController@index');
Route::get('ajax/get_contract_by_customer/{param}', 'AjaxController@getContractByCustomer');
Route::get('ajax/get_machine_by_contract/{param}', 'AjaxController@getMachineByContract');
Route::get('ajax/get_technician_by_ticket_type/{param}/{city}', 'AjaxController@getTechnicianByTicketType');
Route::post('system-management/report/search', 'ReportController@search')->name('report.search');
Route::post('system-management/report/excel', 'ReportController@exportExcel')->name('report.excel');
Route::post('system-management/report/pdf', 'ReportController@exportPDF')->name('report.pdf');

Route::get('avatars/{name}', 'EmployeeManagementController@load');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/realtime-ticketing', 'HomeController@live')->name('live');

Route::get('ajax/on-progress', 'HomeController@progress');
Route::get('ajax/emergencys', 'HomeController@emergency');
Route::get('ajax/over-deadline', 'HomeController@deadline');
Route::get('ajax/finish', 'HomeController@finish');

app/Partners.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Partners extends Model
{
    protected $table = 'partners';
	
    protected $guarded = [];

    public function coverage()
    {
        return $this->hasMany(PartnersCoverage::class, 'partner_id');
    }
}

app/Http/Controllers/PartnersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Response;
use App\Partners;
use App\PartnersCoverage;
use App\Services;
use App\City;
use App\User;


class PartnersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $partners = DB::table('partners')
        ->leftJoin('city', 'partners.city_id', '=', 'city.id')
        ->select('partners.firstname as partner_name', 'partners.*','city.name as city_name')->paginate(5);

        return view('partners/index', ['partners' => $partners]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cities = City::all();
        return view('partners/create', ['cities' => $cities]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateInput($request);
        // Upload image
        $partner = New Partners();
        $partner->lastname         = $request['lastname'];
        $partner->firstname        = $request['firstname'];
        $partner->address          = $request['address'];
        $partner->city_id      	   = $request['city_id'];
        $partner->email            = $request['email'];
        $partner->phone            = $request['phone'];
        $partner->save();
        if($partner){
        	$username = explode("@",$request['email']);
            User::create([
                'username'      => $username[0],
                'email'         => $request['email'],
                'password'      => bcrypt("partners"),
                'firstname'     => $request['firstname'],
                'lastname'      => $request['lastname'],
                'type'			=> 1,
                'roles'			=> 10,
                'employee_id'	=> 0,
                'partner_id'    => $partner->id
            ]);    
        }

        return redirect()->intended('/partners');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
        $partner = Partners::find($id);
        // Redirect to state list if updating state wasn't existed
        if ($partner == null || count($partner) == 0) {
            return redirect()->intended('/partners');
        }
        $cities = City::all();
        return view('partners/view', ['partner' => $partner, 'cities' => $cities]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $partner = Partners::find($id);
        // Redirect to state list if updating state wasn't existed
        if ($partner == null || count($partner) == 0) {
            return redirect()->intended('/partners');
        }
        $cities = City::all();
        return view('partners/edit', ['partner' => $partner, 'cities' => $cities, ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validateInput($request);
        $partner = Partners::findOrFail($id);
        $partner->lastname         = $request['lastname'];
        $partner->firstname        = $request['firstname'];
        $partner->address          = $request['address'];
        $partner->city_id      	   = $request['city_id'];
        $partner->email            = $request['email'];
        $partner->phone            = $request['phone'];
        $partner->save();
        if($partner){
        	$user = User::where('partner_id',$id)->first();
			$user->email         = $request['email'];
	        $user->lastname         = $request['lastname'];
	        $user->firstname        = $request['firstname'];
	        $user->save();
   
        }

        return redirect()->intended('/partners');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Partners::where('id', $id)->delete();
         return redirect()->intended('/partners');
    }

    /**
     * Search state from database base on some specific constraints
     *
     * @param  \Illuminate\Http\Request  $request
     *  @return \Illuminate\Http\Response
     */
    public function search(Request $request) {
        $constraints = [
            'firstname' => $request['firstname'],
            'city.name' => $request['city_name']
            ];
        $partners = $this->doSearchingQuery($constraints);
        $constraints['department_name'] = $request['department_name'];
        return view('partners/index', ['partners' => $partners, 'searchingVals' => $constraints]);
    }

    private function doSearchingQuery($constraints) {
        $query = DB::table('partners')
        ->leftJoin('city', 'partners.city_id', '=', 'city.id')
        ->select('partners.firstname as partner_name', 'partners.*','city.name as city_name');
        $fields = array_keys($constraints);
        $index = 0;
        foreach ($constraints as $constraint) {
            if ($constraint != null) {
                $query = $query->where($fields[$index], 'like', '%'.$constraint.'%');
            }

            $index++;
        }
        return $query->paginate(5);
    }

     /**
     * Load image resource.
     *
     * @param  string  $name
     * @return \Illuminate\Http\Response
     */


    private function validateInput($request) {
        $this->validate($request, [
            'lastname' => 'required|max:60',
            'firstname' => 'required|max:60',
            'phone' => 'required|max:60',
            'address' => 'required|max:120',
            'email' => 'required'
        ]);
    }

    public function addCoverage(Request $request,$id)
    {
        //$this->validateInput($request);

        $coverage = New PartnersCoverage();
        $coverage->partner_id	      	= $id;
        $coverage->city_id        		= $request['city'];
        $coverage->price_install        = $request['install'];
        $coverage->price_service        = $request['service'];
        $coverage->price_maintenance    = $request['maintenance'];
        $coverage->price_toner       	= $request['toner'];
        $coverage->save();

        $return = "<tr>";
        $return .= "<td>".$request['cityname']."</td>";
        $return .= "<td>".$request['install']."</td>";
        $return .= "<td>".$request['service']."</td>";
        $return .= "<td>".$request['maintenance']."</td>";
        $return .= "<td>".$request['toner']."</td>";
        $return .= "<td><a href='javascript:void(0)' class='btn tbn-danger' onclick='delete_action(".$coverage->id.")'>Delete</a></td>";
        $return .= "</tr>";
        return $return;
    }

}

resources/views/partners/create.blade.php
@extends('partners.base')

@section('action-content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add New Partner</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('partners.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Email</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                            <label for="firstname" class="col-md-4 control-label">First Name</label>

                            <div class="col-md-6">
                                <input id="firstname" type="text" class="form-control" name="firstname" value="{{ old('firstname') }}" required autofocus>

                                @if ($errors->has('firstname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                            <label for="lastname" class="col-md-4 control-label">Last Name</label>

                            <div class="col-md-6">
                                <input id="lastname" type="text" class="form-control" name="lastname" value="{{ old('lastname') }}" required>

                                @if ($errors->has('lastname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label">City</label>
                            <div class="col-md-6">
                                <select class="form-control select2" name="city_id" id="city_id">
                                    @foreach ($cities as $city)
                                        <option value="{{$city->id}}">{{$city->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <label for="address" class="col-md-4 control-label">Address</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control" name="address" value="{{ old('address') }}" required>

                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                            <label for="phone" class="col-md-4 control-label">Phone</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control" name="phone" value="{{ old('phone') }}" required>

                                @if ($errors->has('phone'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                       

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Create
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/partners/edit.blade.php
@extends('partners.base')

@section('action-content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Update partner</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('partners.update', ['id' => $partner->id]) }}" enctype="multipart/form-data">
                        <input type="hidden" name="_method" value="PATCH">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Email</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control" name="email" value="{{ old('email') ?: $partner->email }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('firstname') ? ' has-error' : '' }}">
                            <label for="firstname" class="col-md-4 control-label">First Name</label>

                            <div class="col-md-6">
                                <input id="firstname" type="text" class="form-control" name="firstname" value="{{ old('firstname') ?: $partner->firstname  }}" required autofocus>

                                @if ($errors->has('firstname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('firstname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
                            <label for="lastname" class="col-md-4 control-label">Last Name</label>

                            <div class="col-md-6">
                                <input id="lastname" type="text" class="form-control" name="lastname" value="{{ old('lastname') ?: $partner->lastname  }}" required>

                                @if ($errors->has('lastname'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('lastname') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label">City</label>
                            <div class="col-md-6">
                                <select class="form-control select2" name="city_id">
                                    @foreach ($cities as $city)
                                        <option value="{{$city->id}}" {{ ($partner->city_id==$city->id)?"":"" }} >{{$city->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <label for="address" class="col-md-4 control-label">Address</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control" name="address" value="{{ old('address') ?: $partner->address  }}" required>

                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                            <label for="phone" class="col-md-4 control-label">Phone</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control" name="phone" value="{{ old('phone') ?: $partner->phone }}" required>

                                @if ($errors->has('phone'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/partners/index.blade.php
@extends('partners.base')
@section('action-content')
    <!-- Main content -->
    <section class="content">
      <div class="box">
  <div class="box-header">
    <div class="row">
        <div class="col-sm-8">
          <h3 class="box-title">List of partners</h3>
        </div>
        <div class="col-sm-4">
          <a class="btn btn-primary" href="{{ route('partners.create') }}">Add New</a>
        </div>
    </div>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
      <div class="row">
        <div class="col-sm-6"></div>
        <div class="col-sm-6"></div>
      </div>
      <form method="POST" action="{{ route('partners.search') }}">
         {{ csrf_field() }}
         @component('layouts.search', ['title' => 'Search'])
          @component('layouts.two-cols-search-row', ['items' => ['Fullname', 'City'], 
          'oldVals' => [isset($searchingVals) ? $searchingVals['firstname'] : '', isset($searchingVals) ? $searchingVals['city_name'] : '']])
          @endcomponent
        @endcomponent
      </form>
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
      <div class="row">
        <div class="col-sm-12">
          <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
            <thead>
              <tr role="row">
                <th width="10%" class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Name: activate to sort column descending" aria-sort="ascending">Full Name</th>
                <th width="12%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Address: activate to sort column ascending">Address</th>
                <th width="8%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">Email</th>
                <th width="8%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Phone: activate to sort column ascending">Phone</th>
                <th width="8%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="City: activate to sort column ascending">City</th>
                <th tabindex="0" aria-controls="example2" rowspan="1" colspan="2" aria-label="Action: activate to sort column ascending">Action</th>
              </tr>
            </thead>
            <tbody>
            @foreach ($partners as $partner)
                <tr role="row" class="odd">
                  <td class="sorting_1">{{ $partner->firstname }} {{$partner->lastname}}</td>
                  <td class="hidden-xs">{{ $partner->address }}</td>
                  <td class="hidden-xs">{{ $partner->email }}</td>
                  <td class="hidden-xs">{{ $partner->phone }}</td>
                  <td class="hidden-xs">{{ $partner->city_name }}</td>
                  <td>
                    <form class="row" method="POST" action="{{ route('partners.destroy', ['id' => $partner->id]) }}" onsubmit = "return confirm('Are you sure?')">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <a href="{{ route('partners.edit', ['id' => $partner->id]) }}" class="btn btn-warning col-sm-3 col-xs-5 btn-margin">
                        Edit
                        </a>
                        <a href="{{ route('partners.show', ['id' => $partner->id]) }}" class="btn btn-info col-sm-3 col-xs-5 btn-margin">
                        View
                        </a>
                         <button type="submit" class="btn btn-danger col-sm-3 col-xs-5 btn-margin">
                          Delete
                        </button>
                    </form>
                  </td>
              </tr>
            @endforeach
            </tbody>
            <tfoot>
              <tr>
                <tr role="row">
                <th width="10%" class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Name: activate to sort column descending" aria-sort="ascending">Full Name</th>
                <th width="12%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Address: activate to sort column ascending">Address</th>
                <th width="8%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">Email</th>
                <th width="8%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Birthdate: activate to sort column ascending">Phone</th>
                <th width="8%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="HiredDate: activate to sort column ascending">City</th>

                <th tabindex="0" aria-controls="example2" rowspan="1" colspan="2" aria-label="Action: activate to sort column ascending">Action</th>
              </tr>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-5">
          <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to {{count($partners)}} of {{count($partners)}} entries</div>
        </div>
        <div class="col-sm-7">
          <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
            {{ $partners->links() }}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.box-body -->
</div>
    </section>
    <!-- /.content -->
  </div>
@endsection