routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
})->middleware('auth');

Auth::routes();

Route::get('/', 'DashboardController@index');
Route::get('/dashboard', 'DashboardController@index');
// Route::get('/system-management/{option}', 'SystemMgmtController@index');
Route::resource('profile', 'ProfileController'); 
Route::get('/profile', 'ProfileController@index');
Route::post('/profile/update', 'ProfileController@update')->name('profile.update');

Route::post('user-management/search', 'UserManagementController@search')->name('user-management.search');
Route::resource('user-management', 'UserManagementController');

Route::resource('employee-management', 'EmployeeManagementController');
Route::post('employee-management/search', 'EmployeeManagementController@search')->name('employee-management.search');

Route::resource('system-management/department', 'DepartmentController');
Route::post('system-management/department/search', 'DepartmentController@search')->name('department.search');

Route::resource('system-management/division', 'DivisionController');
Route::post('system-management/division/search', 'DivisionController@search')->name('division.search');

Route::resource('system-management/country', 'CountryController');
Route::post('system-management/country/search', 'CountryController@search')->name('country.search');
 
Route::resource('system-management/state', 'StateController');
Route::post('system-management/state/search', 'StateController@search')->name('state.search');

Route::resource('system-management/city', 'CityController');
Route::post('system-management/city/search', 'CityController@search')->name('city.search');

Route::resource('system-management/machine', 'MachineController');
Route::post('system-management/machine/search', 'MachineController@search')->name('machine.search');

Route::resource('system-management/service', 'ServicesController');
Route::post('system-management/service/search', 'ServicesController@search')->name('service.search');

Route::resource('system-management/service-category', 'ServicesCategoryController');
Route::post('system-management/service-category/search', 'ServicesCategoryController@search')->name('service-category.search');

Route::resource('system-management/sla', 'SlaController');
Route::post('system-management/sla/search', 'SlaController@search')->name('sla.search');

Route::resource('partners', 'PartnersController');
Route::post('partners/search', 'PartnersController@search')->name('partners.search');
Route::post('partners/add-coverage/{id}', 'PartnersController@addCoverage')->name('partners.addcoverage');
 
Route::resource('contract', 'ContractsController'); 
Route::get('contract-update', 'ContractsController@updatedata')->name('contract.updatedata');
Route::get('contract/{contract}/delete-machine/{id}', 'ContractsController@destroydetail')->name('contract.deletemachine');
Route::post('contract/update-machine', 'ContractsController@updatemachine')->name('contract.updatemachine');
Route::post('contract/search', 'ContractsController@search')->name('contract.search');

Route::resource('customer', 'CustomerController'); 
Route::post('customer/search', 'CustomerController@search')->name('customer.search');

Route::resource('ticketing', 'TicketingController'); 
Route::post('ticketing/change-technician/{id}', 'TicketingController@updateTechnician')->name('ticketing.update-technician');
Route::get('ticketing-emergency', 'TicketingController@emergency')->name('ticketing.emergencys');
Route::get('ticketing-finish', 'TicketingController@finish')->name('ticketing.finishs');

Route::get('ticketing/approve-request/{id}/{ticket_id}', 'TicketingController@approveRequest')->name('ticketing.approverequest');
Route::get('ticketing/reject-request/{id}/{ticket_id}', 'TicketingController@rejectRequest')->name('ticketing.rejectrequest');
Route::get('ticketing/cancel-request/{id}/{ticket_id}', 'TicketingController@cancelRequest')->name('ticketing.cancelrequest');
Route::post('ticketing/add-request/{id}', 'TicketingController@addRequest')->name('ticketing.addrequest');
Route::post('ticketing/update-request/{id}', 'TicketingController@updateRequest')->name('ticketing.updaterequest');

Route::get('ticketing/closed/{ticket_id}', 'TicketingController@closed')->name('ticketing.closed');
Route::get('ticketing/decline-closed/{ticket_id}', 'TicketingController@declineClosed')->name('ticketing.declineclosed');
Route::get('ticketing/approve-closed/{ticket_id}', 'TicketingController@approveClosed')->name('ticketing.approveclosed');
Route::post('ticketing/search', 'TicketingController@search')->name('ticketing.search');
Route::get('ticketing/add/{id}', 'TicketingController@add')->name('ticketing.add');
Route::post('ticketing/add-action/{id}', 'TicketingController@addAction')->name('ticketing.addaction');


Route::get('system-management/report', 'ReportController@index');
Route::get('ajax/get_contract_by_customer/{param}', 'AjaxController@getContractByCustomer');
Route::get('ajax/get_machine_by_contract/{param}', 'AjaxController@getMachineByContract');
Route::get('ajax/get_technician_by_ticket_type/{param}/{city}', 'AjaxController@getTechnicianByTicketType');
Route::post('system-management/report/search', 'ReportController@search')->name('report.search');
Route::post('system-management/report/excel', 'ReportController@exportExcel')->name('report.excel');
Route::post('system-management/report/pdf', 'ReportController@exportPDF')->name('report.pdf');

Route::get('avatars/{name}', 'EmployeeManagementController@load');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/realtime-ticketing', 'HomeController@live')->name('live');

Route::get('ajax/on-progress', 'HomeController@progress');
Route::get('ajax/emergencys', 'HomeController@emergency');
Route::get('ajax/over-deadline', 'HomeController@deadline');
Route::get('ajax/finish', 'HomeController@finish');

app/Sla.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sla extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'sla';


    /**
    * The attributes that aren't mass assignable.
    *
    * @var array
    */
    protected $guarded = [];

}

app/Http/Controllers/SlaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Sla;

class SlaController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slas = Sla::paginate(10);

        return view('system-mgmt/sla/index', ['slas' => $slas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('system-mgmt/sla/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validateInput($request);
         Sla::create([
            'name' => $request['name'],
            'code' => $request['code'],
            'maximum' => $request['maximum']
        ]);

        return redirect()->intended('system-management/sla');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sla = sla::find($id);
        // Redirect to sla list if updating sla wasn't existed
        if ($sla == null || count($sla) == 0) {
            return redirect()->intended('/system-management/sla');
        }

        return view('system-mgmt/sla/edit', ['sla' => $sla]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $sla = sla::findOrFail($id);
        $input = [
            'name' => $request['name'],
            'code' => $request['code'],
            'maximum' => $request['maximum']
        ];
        $this->validate($request, [
        'name' => 'required|max:60'
        ]);
        sla::where('id', $id)
            ->update($input);
        
        return redirect()->intended('system-management/sla');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        sla::where('id', $id)->softDeletes();
        return redirect()->intended('system-management/sla');
    }

    /**
     * Search sla from database base on some specific constraints
     *
     * @param  \Illuminate\Http\Request  $request
     *  @return \Illuminate\Http\Response
     */
    public function search(Request $request) {
        $constraints = [
            'name' => $request['name'],
            'code' => $request['code']
            ];

       $slas = $this->doSearchingQuery($constraints);
       return view('system-mgmt/sla/index', ['slas' => $slas, 'searchingVals' => $constraints]);
    }

    private function doSearchingQuery($constraints) {
        $query = sla::query();
        $fields = array_keys($constraints);
        $index = 0;
        foreach ($constraints as $constraint) {
            if ($constraint != null) {
                $query = $query->where( $fields[$index], 'like', '%'.$constraint.'%');
            }

            $index++;
        }
        return $query->paginate(5);
    }

    private function validateInput($request) {
        $this->validate($request, [
        'name' => 'required|max:60|unique:sla',
        'code' => 'required|max:6|unique:sla',
        'maximum' => 'required|unique:sla'
        ]);
    }
}

resources/views/system-mgmt/sla/base.blade.php
@extends('layouts.app-template')
@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        SLA Mangement
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> System Mangement</a></li>
        <li class="active">Service Level Aggrement</li>
      </ol>
    </section>
    @yield('action-content')
    <!-- /.content -->
  </div>
@endsection

resources/views/system-mgmt/sla/create.blade.php
@extends('system-mgmt.sla.base')

@section('action-content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add new sla</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('sla.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">SLA Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
						
						<div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
                            <label for="code" class="col-md-4 control-label">SLA Code</label>

                            <div class="col-md-6">
                                <input id="code" type="text" class="form-control" name="code" value="{{ old('code') }}" required autofocus>

                                @if ($errors->has('code'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('maximum') ? ' has-error' : '' }}">
                            <label for="maximum" class="col-md-4 control-label">Maximum Hours</label>

                            <div class="col-md-6">
                                <input id="maximum" type="number" class="form-control" name="maximum" value="{{ old('maximum') }}" required autofocus>

                                @if ($errors->has('maximum'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('maximum') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Create
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/system-mgmt/sla/edit.blade.php
@extends('system-mgmt.sla.base')

@section('action-content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Update SLA</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('sla.update', ['id' => $sla->id]) }}">
                        <input type="hidden" name="_method" value="PATCH">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label"> SLA Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') ?: $sla->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
						
						<div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
                            <label for="code" class="col-md-4 control-label">SLA Code</label>

                            <div class="col-md-6">
                                <input id="code" type="text" class="form-control" name="code" value="{{ old('code') ?: $sla->code }}" required autofocus>

                                @if ($errors->has('code'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('maximum') ? ' has-error' : '' }}">
                            <label for="maximum" class="col-md-4 control-label">Maximum Hours</label>

                            <div class="col-md-6">
                                <input id="maximum" type="number" class="form-control" name="maximum" value="{{ old('maximum') ?: $sla->maximum }}" required autofocus>

                                @if ($errors->has('maximum'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('maximum') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
						
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/system-mgmt/sla/index.blade.php
@extends('system-mgmt.sla.base')
@section('action-content')
    <!-- Main content -->
    <section class="content">
      <div class="box">
  <div class="box-header">
    <div class="row">
        <div class="col-sm-8">
          <h3 class="box-title">List of SLA</h3>
        </div>
        <div class="col-sm-4">
          <a class="btn btn-primary" href="{{ route('sla.create') }}">Add new sla</a>
        </div>
    </div>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
      <div class="row">
        <div class="col-sm-6"></div>
        <div class="col-sm-6"></div>
      </div>
      <form method="POST" action="{{ route('sla.search') }}">
         {{ csrf_field() }}
         @component('layouts.search', ['title' => 'Search'])
          @component('layouts.two-cols-search-row', ['items' => ['Name'], 
          'oldVals' => [isset($searchingVals) ? $searchingVals['name'] : '']])
          @endcomponent
        @endcomponent
      </form>
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
      <div class="row">
        <div class="col-sm-12">
          <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
            <thead>
              <tr role="row">
                
                <th width="20%" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="code: activate to sort column ascending">Code</th>
				<th width="20%" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="sla: activate to sort column ascending">Name</th>
        <th width="20%" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="sla: activate to sort column ascending">Maximum</th>
                <th tabindex="0" aria-controls="example2" rowspan="1" colspan="2" aria-label="Action: activate to sort column ascending">Action</th>
              </tr>
            </thead>
            <tbody>
            {{$slas}}
            @foreach ($slas as $sla)
                <tr role="row" class="odd">
                  <td>{{ $sla->code }}</td>
                  <td>{{ $sla->name }}</td>
                  <td>{{ $sla->maximum }}</td>
                  <td>
                    <form class="row" method="POST" action="{{ route('sla.destroy', ['id' => $sla->id]) }}" onsubmit = "return confirm('Are you sure?')">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <a href="{{ route('sla.edit', ['id' => $sla->id]) }}" class="btn btn-warning col-sm-3 col-xs-5 btn-margin">
                        Edit
                        </a>
                        <button type="submit" class="btn btn-danger col-sm-3 col-xs-5 btn-margin">
                          Delete
                        </button>
                    </form>
                  </td>
              </tr>
            @endforeach
            </tbody>
            <tfoot>
              <tr>
                <th width="20%" rowspan="1" colspan="1">Code</th>
                <th width="20%" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="sla: activate to sort column ascending">Machine Name</th>
                <th rowspan="1" colspan="2">Action</th>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-5">
          <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to {{count($slas)}} of {{count($slas)}} entries</div>
        </div>
        <div class="col-sm-7">
          <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
            {{ $slas->links() }}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.box-body -->
</div>
    </section>
    <!-- /.content -->
  </div>
@endsection